import { z } from "zod";

// ─── Schedule L Balance Sheet (shared between BOY and EOY) ──────────────────

const assetsSchema = z.object({
  cash: z.number().nullable(),
  tradeNotesAndReceivables_gross: z.number().nullable(),
  tradeNotesAndReceivables_allowance: z.number().nullable(),
  tradeNotesAndReceivables_net: z.number().nullable(),
  inventories: z.number().nullable(),
  usGovernmentObligations: z.number().nullable(),
  taxExemptSecurities: z.number().nullable(),
  otherCurrentAssets: z.number().nullable(),
  loansToShareholders: z.number().nullable(),
  mortgageAndRealEstate: z.number().nullable(),
  otherInvestments: z.number().nullable(),
  buildingsAndOtherDepreciable_gross: z.number().nullable(),
  buildingsAndOtherDepreciable_accumulatedDepreciation: z.number().nullable(),
  buildingsAndOtherDepreciable_net: z.number().nullable(),
  depletableAssets_gross: z.number().nullable(),
  depletableAssets_accumulatedDepletion: z.number().nullable(),
  depletableAssets_net: z.number().nullable(),
  land: z.number().nullable(),
  intangibleAssets_gross: z.number().nullable(),
  intangibleAssets_accumulatedAmortization: z.number().nullable(),
  intangibleAssets_net: z.number().nullable(),
  otherAssets: z.number().nullable(),
  totalAssets: z.number().nullable(),
}).passthrough();

const liabilitiesAndEquitySchema = z.object({
  accountsPayable: z.number().nullable(),
  mortgagesNotesPayable_lessThan1Year: z.number().nullable(),
  otherCurrentLiabilities: z.number().nullable(),
  loansFromShareholders: z.number().nullable(),
  mortgagesNotesPayable_1YearOrMore: z.number().nullable(),
  otherLiabilities: z.number().nullable(),
  totalLiabilities: z.number().nullable(),
  capitalStock_preferred: z.number().nullable(),
  capitalStock_common: z.number().nullable(),
  additionalPaidInCapital: z.number().nullable(),
  retainedEarnings_appropriated: z.number().nullable(),
  retainedEarnings_unappropriated: z.number().nullable(),
  adjustmentsToShareholderEquity: z.number().nullable(),
  lessShareholderTreasuryStock: z.number().nullable(),
  totalLiabilitiesAndEquity: z.number().nullable(),
}).passthrough();

const balanceSheetPeriodSchema = z.object({
  assets: assetsSchema,
  liabilitiesAndEquity: liabilitiesAndEquitySchema,
}).passthrough();

const scheduleLSchema = z.object({
  beginningOfYear: balanceSheetPeriodSchema,
  endOfYear: balanceSheetPeriodSchema,
}).passthrough();

// ─── Officer Compensation ───────────────────────────────────────────────────

const officerCompensationSchema = z.object({
  name: z.string().nullable(),
  ssn_last4: z.string().nullable(),
  percentTimeDevoted: z.number().nullable(),
  percentStockOwned_common: z.number().nullable(),
  percentStockOwned_preferred: z.number().nullable(),
  compensationAmount: z.number().nullable(),
}).passthrough();

// ─── Form 1120 Schema ──────────────────────────────────────────────────────

export const form1120Schema = z.object({
  metadata: z.object({
    taxYear: z.number().nullable(),
    corporationName: z.string().nullable(),
    ein: z.string().nullable(),
    address: z.string().nullable(),
    dateIncorporated: z.string().nullable(),
    totalAssets: z.number().nullable(),
    accountingMethod: z.string().nullable(),
    businessActivityCode: z.string().nullable(),
  }).passthrough(),
  income: z.object({
    grossReceipts_line1a: z.number().nullable(),
    returnsAllowances_line1b: z.number().nullable(),
    balanceAfterReturns_line1c: z.number().nullable(),
    costOfGoodsSold_line2: z.number().nullable(),
    grossProfit_line3: z.number().nullable(),
    dividendsReceived_line4: z.number().nullable(),
    interestIncome_line5: z.number().nullable(),
    grossRents_line6: z.number().nullable(),
    grossRoyalties_line7: z.number().nullable(),
    capitalGainNet_line8: z.number().nullable(),
    netGainForm4797_line9: z.number().nullable(),
    otherIncome_line10: z.number().nullable(),
    totalIncome_line11: z.number().nullable(),
  }).passthrough(),
  deductions: z.object({
    compensationOfOfficers_line12: z.number().nullable(),
    salariesAndWages_line13: z.number().nullable(),
    repairsAndMaintenance_line14: z.number().nullable(),
    badDebts_line15: z.number().nullable(),
    rents_line16: z.number().nullable(),
    taxesAndLicenses_line17: z.number().nullable(),
    interestExpense_line18: z.number().nullable(),
    charitableContributions_line19: z.number().nullable(),
    depreciationForm4562_line20: z.number().nullable(),
    depletion_line21: z.number().nullable(),
    advertising_line22: z.number().nullable(),
    pensionProfitSharing_line23: z.number().nullable(),
    employeeBenefitPrograms_line24: z.number().nullable(),
    energyEfficientBuildings_line25: z.number().nullable(),
    otherDeductions_line26: z.number().nullable(),
    totalDeductions_line27: z.number().nullable(),
  }).passthrough(),
  taxableIncome: z.object({
    taxableIncomeBeforeNOL_line28: z.number().nullable(),
    netOperatingLossDeduction_line29a: z.number().nullable(),
    specialDeductions_line29b: z.number().nullable(),
    totalSpecialDeductions_line29c: z.number().nullable(),
    taxableIncome_line30: z.number().nullable(),
  }).passthrough(),
  taxAndPayments: z.object({
    totalTax_line31: z.number().nullable(),
    totalPaymentsAndCredits_line32: z.number().nullable(),
    estimatedTaxPenalty_line33: z.number().nullable(),
    amountOwed_line34: z.number().nullable(),
    overpayment_line35: z.number().nullable(),
    refundedAmount_line36: z.number().nullable(),
    creditToNextYear_line36: z.number().nullable(),
  }).passthrough(),
  scheduleC: z.object({
    dividendsFromDomesticCorps: z.number().nullable(),
    dividendsFromForeignCorps: z.number().nullable(),
    dividendsReceivedDeduction: z.number().nullable(),
    totalDividends: z.number().nullable(),
    totalSpecialDeductions: z.number().nullable(),
  }).passthrough().nullable().default(null),
  scheduleJ: z.object({
    taxRateAmount_line2: z.number().nullable(),
    alternativeMinimumTax_line3: z.number().nullable(),
    totalTax_line4: z.number().nullable(),
    foreignTaxCredit_line5a: z.number().nullable(),
    generalBusinessCredit_line5b: z.number().nullable(),
    priorYearMinimumTax_line5d: z.number().nullable(),
    totalCredits_line5e: z.number().nullable(),
    subtotal_line6: z.number().nullable(),
    personalHoldingCompanyTax_line7: z.number().nullable(),
    recaptureCredits_line8: z.number().nullable(),
    totalTax_line10: z.number().nullable(),
    estimatedTaxPayments_line11: z.number().nullable(),
    overpaymentCredited_line12: z.number().nullable(),
    extensionPayment_line13: z.number().nullable(),
    federalTaxOnFuels_line14: z.number().nullable(),
    totalPayments_line18: z.number().nullable(),
    taxDue_line19: z.number().nullable(),
    overpayment_line20: z.number().nullable(),
  }).passthrough().nullable().default(null),
  scheduleK: z.object({
    cashDistributions: z.number().nullable(),
    propertyDistributions: z.number().nullable(),
    stockDividends: z.number().nullable(),
  }).passthrough().nullable().default(null),
  scheduleL: scheduleLSchema.nullable().default(null),
  scheduleM1: z.object({
    netIncomePerBooks_line1: z.number().nullable(),
    federalIncomeTax_line2: z.number().nullable(),
    excessCapitalLossesOverGains_line3: z.number().nullable(),
    incomeSubjectToTaxNotOnBooks_line4: z.number().nullable(),
    expensesOnBooksNotOnReturn_line5: z.number().nullable(),
    totalAdditions_line6: z.number().nullable(),
    incomeOnReturnNotInBooks_line7: z.number().nullable(),
    deductionsNotOnBooks_line8: z.number().nullable(),
    totalSubtractions_line9: z.number().nullable(),
    incomePerReturn_line10: z.number().nullable(),
  }).passthrough().nullable().default(null),
  scheduleM2: z.object({
    balanceBeginningOfYear_line1: z.number().nullable(),
    netIncomePerBooks_line2: z.number().nullable(),
    otherIncreases_line3: z.number().nullable(),
    total_line4: z.number().nullable(),
    distributions_cashProperty_line5a: z.number().nullable(),
    distributions_stock_line5b: z.number().nullable(),
    otherDecreases_line6: z.number().nullable(),
    total_line7: z.number().nullable(),
    balanceEndOfYear_line8: z.number().nullable(),
  }).passthrough().nullable().default(null),
  officerCompensation: z.array(officerCompensationSchema).default([]),
  costOfGoodsSold: z.object({
    inventoryBeginning_line1: z.number().nullable(),
    purchases_line2: z.number().nullable(),
    laborCost_line3: z.number().nullable(),
    additionalSection263A_line4: z.number().nullable(),
    otherCosts_line5: z.number().nullable(),
    total_line6: z.number().nullable(),
    inventoryEnding_line7: z.number().nullable(),
    costOfGoodsSold_line8: z.number().nullable(),
    inventoryMethod: z.string().nullable(),
  }).passthrough().nullable().default(null),
  extractionNotes: z.array(z.string()).default([]),
}).passthrough();

export type Form1120Data = z.infer<typeof form1120Schema>;
