import { z } from "zod";

// ─── Schedule L Balance Sheet ───────────────────────────────────────────────

const scheduleLAssetsSchema = z.object({
  cash: z.number().nullable(),
  tradeNotesAndReceivables_gross: z.number().nullable(),
  tradeNotesAndReceivables_allowance: z.number().nullable(),
  tradeNotesAndReceivables_net: z.number().nullable(),
  inventories: z.number().nullable(),
  usGovernmentObligations: z.number().nullable(),
  taxExemptSecurities: z.number().nullable(),
  otherCurrentAssets: z.number().nullable(),
  loansToShareholders: z.number().nullable(),
  mortgageAndRealEstate: z.number().nullable(),
  otherInvestments: z.number().nullable(),
  buildingsAndOtherDepreciable_gross: z.number().nullable(),
  buildingsAndOtherDepreciable_accumulatedDepreciation: z.number().nullable(),
  buildingsAndOtherDepreciable_net: z.number().nullable(),
  depletableAssets_gross: z.number().nullable(),
  depletableAssets_accumulatedDepletion: z.number().nullable(),
  depletableAssets_net: z.number().nullable(),
  land: z.number().nullable(),
  intangibleAssets_gross: z.number().nullable(),
  intangibleAssets_accumulatedAmortization: z.number().nullable(),
  intangibleAssets_net: z.number().nullable(),
  otherAssets: z.number().nullable(),
  totalAssets: z.number().nullable(),
}).passthrough();

const scheduleLLiabilitiesAndEquitySchema = z.object({
  accountsPayable: z.number().nullable(),
  mortgagesNotesPayable_lessThan1Year: z.number().nullable(),
  otherCurrentLiabilities: z.number().nullable(),
  loansFromShareholders: z.number().nullable(),
  mortgagesNotesPayable_1YearOrMore: z.number().nullable(),
  otherLiabilities: z.number().nullable(),
  totalLiabilities: z.number().nullable(),
  capitalStock: z.number().nullable(),
  additionalPaidInCapital: z.number().nullable(),
  retainedEarnings: z.number().nullable(),
  adjustmentsToShareholderEquity: z.number().nullable(),
  lessShareholderTreasuryStock: z.number().nullable(),
  totalLiabilitiesAndEquity: z.number().nullable(),
}).passthrough();

const scheduleLPeriodSchema = z.object({
  assets: scheduleLAssetsSchema,
  liabilitiesAndEquity: scheduleLLiabilitiesAndEquitySchema,
}).passthrough();

// ─── Officer Compensation ───────────────────────────────────────────────────

const officerCompensationSchema = z.object({
  name: z.string().nullable(),
  ssn_last4: z.string().nullable(),
  percentTimeDevoted: z.number().nullable(),
  percentStockOwned: z.number().nullable(),
  compensationAmount: z.number().nullable(),
}).passthrough();

// ─── Form 1120-S Schema ────────────────────────────────────────────────────

export const form1120SSchema = z.object({
  metadata: z.object({
    taxYear: z.number().nullable(),
    corporationName: z.string().nullable(),
    ein: z.string().nullable(),
    address: z.string().nullable(),
    dateIncorporated: z.string().nullable(),
    dateSElectionEffective: z.string().nullable(),
    totalAssets: z.number().nullable(),
    accountingMethod: z.string().nullable(),
    businessActivityCode: z.string().nullable(),
    numberOfShareholders: z.number().nullable(),
  }).passthrough(),
  income: z.object({
    grossReceipts_line1a: z.number().nullable(),
    returnsAllowances_line1b: z.number().nullable(),
    balanceAfterReturns_line1c: z.number().nullable(),
    costOfGoodsSold_line2: z.number().nullable(),
    grossProfit_line3: z.number().nullable(),
    netGainForm4797_line4: z.number().nullable(),
    otherIncome_line5: z.number().nullable(),
    totalIncome_line6: z.number().nullable(),
  }).passthrough(),
  deductions: z.object({
    compensationOfOfficers_line7: z.number().nullable(),
    salariesAndWages_line8: z.number().nullable(),
    repairsAndMaintenance_line9: z.number().nullable(),
    badDebts_line10: z.number().nullable(),
    rents_line11: z.number().nullable(),
    taxesAndLicenses_line12: z.number().nullable(),
    interestExpense_line13: z.number().nullable(),
    depreciationNotOnForm4562_line14a: z.number().nullable(),
    depreciationFromForm4562_line14b: z.number().nullable(),
    totalDepreciation_line14c: z.number().nullable(),
    depletion_line15: z.number().nullable(),
    advertising_line16: z.number().nullable(),
    pensionProfitSharing_line17: z.number().nullable(),
    employeeBenefitPrograms_line18: z.number().nullable(),
    energyEfficientBuildings_line19: z.number().nullable(),
    otherDeductions_line20: z.number().nullable(),
    totalDeductions_line21: z.number().nullable(),
  }).passthrough(),
  ordinaryBusinessIncome_line22: z.number().nullable(),
  taxAndPayments: z.object({
    excessNetPassiveIncomeTax_line23a: z.number().nullable(),
    builtInGainsTax_line23b: z.number().nullable(),
    totalTax_line23c: z.number().nullable(),
    estimatedTaxPayments_line24a: z.number().nullable(),
    taxDeposited_line24b: z.number().nullable(),
    creditForFederalTaxOnFuels_line24c: z.number().nullable(),
    totalPayments_line24d: z.number().nullable(),
    estimatedTaxPenalty_line25: z.number().nullable(),
    amountOwed_line26: z.number().nullable(),
    overpayment_line27: z.number().nullable(),
    creditToNextYear_line28: z.number().nullable(),
  }).passthrough(),
  scheduleK: z.object({
    incomeAndLoss: z.object({
      ordinaryBusinessIncome_line1: z.number().nullable(),
      netRentalRealEstateIncome_line2: z.number().nullable(),
      otherNetRentalIncome_line3: z.number().nullable(),
      interestIncome_line4: z.number().nullable(),
      ordinaryDividends_line5a: z.number().nullable(),
      qualifiedDividends_line5b: z.number().nullable(),
      royalties_line6: z.number().nullable(),
      netShortTermCapitalGain_line7: z.number().nullable(),
      netLongTermCapitalGain_line8a: z.number().nullable(),
      collectiblesGain_line8b: z.number().nullable(),
      unrealizedSection1250Gain_line8c: z.number().nullable(),
      netSection1231Gain_line9: z.number().nullable(),
      otherIncome_line10: z.number().nullable(),
    }).passthrough(),
    deductions: z.object({
      section179Deduction_line11: z.number().nullable(),
      otherDeductions_line12a: z.number().nullable(),
      charitableContributions_line12a_detail: z.number().nullable(),
    }).passthrough(),
    credits: z.object({
      lowIncomeHousingCredit_line13a: z.number().nullable(),
      lowIncomeHousingCredit_other_line13b: z.number().nullable(),
      qualifiedRehabExpenses_line13c: z.number().nullable(),
      otherRentalRealEstateCredits_line13d: z.number().nullable(),
      otherRentalCredits_line13e: z.number().nullable(),
      otherCredits_line13f: z.number().nullable(),
    }).passthrough(),
    foreignTransactions: z.object({
      foreignCountry: z.string().nullable(),
      grossIncomeForeign_line14a: z.number().nullable(),
      foreignTaxesPaid_line14l: z.number().nullable(),
      foreignTaxesAccrued_line14m: z.number().nullable(),
    }).passthrough(),
    alternativeMinimumTax: z.object({
      amtAdjustments_line15a: z.number().nullable(),
      amtAdjustmentsPost2017_line15b: z.number().nullable(),
      depletionAdjustment_line15c: z.number().nullable(),
      amtOilGasDeduction_line15d: z.number().nullable(),
      otherAMTItems_line15e: z.number().nullable(),
    }).passthrough(),
    distributions: z.object({
      cashAndMarketableSecurities_line16a: z.number().nullable(),
      propertyDistributions_line16b: z.number().nullable(),
      repaymentOfLoansFromShareholders_line16c: z.number().nullable(),
    }).passthrough(),
    otherItems: z.object({
      investmentIncome_line17a: z.number().nullable(),
      investmentExpenses_line17b: z.number().nullable(),
      dividendEquivalents_line17c: z.number().nullable(),
    }).passthrough(),
  }).passthrough(),
  scheduleL: z.object({
    beginningOfYear: scheduleLPeriodSchema,
    endOfYear: scheduleLPeriodSchema,
  }).passthrough().nullable().default(null),
  scheduleM1: z.object({
    netIncomePerBooks_line1: z.number().nullable(),
    incomeOnScheduleKNotOnBooks_line2: z.number().nullable(),
    expensesOnBooksNotOnScheduleK_line3a: z.number().nullable(),
    depreciation_line3a: z.number().nullable(),
    travelEntertainment_line3b: z.number().nullable(),
    total_line4: z.number().nullable(),
    incomeOnBooksNotOnScheduleK_line5: z.number().nullable(),
    deductionsOnScheduleKNotOnBooks_line6a: z.number().nullable(),
    depreciation_line6a: z.number().nullable(),
    total_line7: z.number().nullable(),
    incomeOnScheduleK_line8: z.number().nullable(),
  }).passthrough().nullable().default(null),
  scheduleM2: z.object({
    otherAdjustmentsAccount: z.object({
      balanceBeginningOfYear_line1: z.number().nullable(),
      ordinaryIncome_line2: z.number().nullable(),
      otherAdditions_line3: z.number().nullable(),
      total_line4: z.number().nullable(),
      distributions_line5: z.number().nullable(),
      otherReductions_line6: z.number().nullable(),
      total_line7: z.number().nullable(),
      balanceEndOfYear_line8: z.number().nullable(),
    }).passthrough(),
    accumulatedAdjustmentsAccount: z.object({
      balanceBeginningOfYear_line1: z.number().nullable(),
      ordinaryIncome_line2: z.number().nullable(),
      otherAdditions_line3: z.number().nullable(),
      total_line4: z.number().nullable(),
      distributions_line5: z.number().nullable(),
      otherReductions_line6: z.number().nullable(),
      total_line7: z.number().nullable(),
      balanceEndOfYear_line8: z.number().nullable(),
    }).passthrough(),
    shareholdersUndistributedTaxableIncome: z.object({
      balanceBeginningOfYear_line1: z.number().nullable(),
      balanceEndOfYear_line8: z.number().nullable(),
    }).passthrough(),
  }).passthrough().nullable().default(null),
  officerCompensation: z.array(officerCompensationSchema).default([]),
  costOfGoodsSold: z.object({
    inventoryBeginning_line1: z.number().nullable(),
    purchases_line2: z.number().nullable(),
    laborCost_line3: z.number().nullable(),
    additionalSection263A_line4: z.number().nullable(),
    otherCosts_line5: z.number().nullable(),
    total_line6: z.number().nullable(),
    inventoryEnding_line7: z.number().nullable(),
    costOfGoodsSold_line8: z.number().nullable(),
    inventoryMethod: z.string().nullable(),
  }).passthrough().nullable().default(null),
  extractionNotes: z.array(z.string()).default([]),
}).passthrough();

export type Form1120SData = z.infer<typeof form1120SSchema>;
