import { z } from "zod";

const breakdownItemSchema = z.object({
  category: z.string().nullable(),
  amount: z.number().nullable(),
}).passthrough();

const addBackDetailSchema = z.object({
  description: z.string().nullable(),
  amount: z.number().nullable(),
  reason: z.string().nullable(),
}).passthrough();

export const pnlSchema = z.object({
  metadata: z.object({
    businessName: z.string().nullable(),
    periodStart: z.string().nullable(),
    periodEnd: z.string().nullable(),
    periodType: z.enum(["monthly", "quarterly", "annual", "ytd", "custom"]).nullable(),
    preparedBy: z.string().nullable(),
    basis: z.enum(["cash", "accrual"]).nullable(),
  }).passthrough(),
  revenue: z.object({
    grossRevenue: z.number().nullable(),
    salesReturnsAndAllowances: z.number().nullable(),
    salesDiscounts: z.number().nullable(),
    netRevenue: z.number().nullable(),
    revenueBreakdown: z.array(breakdownItemSchema).default([]),
  }).passthrough(),
  costOfGoodsSold: z.object({
    beginningInventory: z.number().nullable(),
    purchases: z.number().nullable(),
    directLabor: z.number().nullable(),
    directMaterials: z.number().nullable(),
    manufacturingOverhead: z.number().nullable(),
    freightIn: z.number().nullable(),
    endingInventory: z.number().nullable(),
    totalCOGS: z.number().nullable(),
    cogsBreakdown: z.array(breakdownItemSchema).default([]),
  }).passthrough(),
  grossProfit: z.number().nullable(),
  grossProfitMargin: z.number().nullable(),
  operatingExpenses: z.object({
    salariesAndWages: z.number().nullable(),
    officerCompensation: z.number().nullable(),
    payrollTaxes: z.number().nullable(),
    employeeBenefits: z.number().nullable(),
    rent: z.number().nullable(),
    utilities: z.number().nullable(),
    insurance: z.number().nullable(),
    officeExpenses: z.number().nullable(),
    advertising: z.number().nullable(),
    professionalFees: z.number().nullable(),
    legal: z.number().nullable(),
    accounting: z.number().nullable(),
    repairs: z.number().nullable(),
    maintenance: z.number().nullable(),
    depreciation: z.number().nullable(),
    amortization: z.number().nullable(),
    travel: z.number().nullable(),
    meals: z.number().nullable(),
    entertainment: z.number().nullable(),
    vehicleExpenses: z.number().nullable(),
    bankCharges: z.number().nullable(),
    interest: z.number().nullable(),
    taxesAndLicenses: z.number().nullable(),
    badDebtExpense: z.number().nullable(),
    charitableContributions: z.number().nullable(),
    education: z.number().nullable(),
    subscriptions: z.number().nullable(),
    telephone: z.number().nullable(),
    internet: z.number().nullable(),
    software: z.number().nullable(),
    contractLabor: z.number().nullable(),
    commissionsAndFees: z.number().nullable(),
    otherExpenses: z.number().nullable(),
    totalOperatingExpenses: z.number().nullable(),
    expenseBreakdown: z.array(breakdownItemSchema).default([]),
  }).passthrough(),
  operatingIncome: z.number().nullable(),
  otherIncomeAndExpenses: z.object({
    interestIncome: z.number().nullable(),
    interestExpense: z.number().nullable(),
    gainOnSaleOfAssets: z.number().nullable(),
    lossOnSaleOfAssets: z.number().nullable(),
    otherIncome: z.number().nullable(),
    otherExpenses: z.number().nullable(),
    totalOtherNet: z.number().nullable(),
  }).passthrough(),
  incomeBeforeTax: z.number().nullable(),
  incomeTaxExpense: z.number().nullable(),
  netIncome: z.number().nullable(),
  netIncomeMargin: z.number().nullable(),
  addBacks: z.object({
    depreciation: z.number().nullable(),
    amortization: z.number().nullable(),
    interestExpense: z.number().nullable(),
    ownerCompensation: z.number().nullable(),
    oneTimeExpenses: z.number().nullable(),
    nonRecurringItems: z.number().nullable(),
    personalExpenses: z.number().nullable(),
    totalAddBacks: z.number().nullable(),
    adjustedNetIncome: z.number().nullable(),
    addBackDetails: z.array(addBackDetailSchema).default([]),
  }).passthrough(),
  ebitda: z.number().nullable(),
  priorPeriodComparison: z.object({
    hasPriorPeriod: z.boolean().nullable(),
    priorPeriodStart: z.string().nullable(),
    priorPeriodEnd: z.string().nullable(),
    priorGrossRevenue: z.number().nullable(),
    priorNetIncome: z.number().nullable(),
    revenueGrowthPercent: z.number().nullable(),
    netIncomeGrowthPercent: z.number().nullable(),
  }).passthrough(),
  extractionNotes: z.array(z.string()).default([]),
}).passthrough();

export type PnlData = z.infer<typeof pnlSchema>;
