import { z } from "zod";

const testResultSchema = z.object({
  testName: z.string().nullable(),
  testCategory: z.enum([
    "identity",
    "purity",
    "potency",
    "sterility",
    "endotoxin",
    "safety",
    "physical",
    "conjugation",
    "other",
  ]).nullable(),
  method: z.string().nullable(),
  specification: z.string().nullable(),
  result: z.string().nullable(),
  unit: z.string().nullable(),
  numericResult: z.number().nullable(),
  pass: z.boolean().nullable(),
  reportReference: z.string().nullable(),
}).passthrough();

const identityTestsSchema = z.object({
  peptideMap: z.string().nullable(),
  peptideMapPass: z.boolean().nullable(),
  intactMass: z.number().nullable(),
  intactMassUnit: z.string().nullable(),
  intactMassPass: z.boolean().nullable(),
  glycosylationProfile: z.string().nullable(),
  westernBlot: z.string().nullable(),
  westernBlotPass: z.boolean().nullable(),
  isoelectricFocusing: z.string().nullable(),
}).passthrough();

const purityTestsSchema = z.object({
  secHplcMonomer: z.number().nullable(),
  secHplcAggregate: z.number().nullable(),
  secHplcFragment: z.number().nullable(),
  secHplcPass: z.boolean().nullable(),
  hicMainPeak: z.number().nullable(),
  hicPass: z.boolean().nullable(),
  ceDsReducedPurity: z.number().nullable(),
  ceDsNonReducedPurity: z.number().nullable(),
  residualHostCellProtein: z.number().nullable(),
  residualHostCellProteinUnit: z.string().nullable(),
  residualHostCellProteinPass: z.boolean().nullable(),
  residualDna: z.number().nullable(),
  residualDnaUnit: z.string().nullable(),
  residualDnaPass: z.boolean().nullable(),
  residualProteinA: z.number().nullable(),
  residualProteinAUnit: z.string().nullable(),
  residualProteinAPass: z.boolean().nullable(),
}).passthrough();

const potencyTestsSchema = z.object({
  cytotoxicityIC50: z.number().nullable(),
  cytotoxicityIC50Unit: z.string().nullable(),
  cytotoxicityRelativePotency: z.number().nullable(),
  cytotoxicityPass: z.boolean().nullable(),
  adccActivity: z.number().nullable(),
  adccActivityUnit: z.string().nullable(),
  adccPass: z.boolean().nullable(),
  bindingAffinity: z.number().nullable(),
  bindingAffinityUnit: z.string().nullable(),
  bindingAffinityMethod: z.string().nullable(),
  bindingAffinityPass: z.boolean().nullable(),
}).passthrough();

const conjugationTestsSchema = z.object({
  dar: z.number().nullable(),
  darMethod: z.string().nullable(),
  darSpec: z.string().nullable(),
  darPass: z.boolean().nullable(),
  freePayloadPercent: z.number().nullable(),
  freePayloadSpec: z.string().nullable(),
  freePayloadPass: z.boolean().nullable(),
  freeAntibodyPercent: z.number().nullable(),
  freeAntibodyPass: z.boolean().nullable(),
}).passthrough();

export const certificateOfAnalysisSchema = z.object({
  metadata: z.object({
    productName: z.string().nullable(),
    productCode: z.string().nullable(),
    batchNumber: z.string().nullable(),
    lotNumber: z.string().nullable(),
    dateOfManufacture: z.string().nullable(),
    dateOfAnalysis: z.string().nullable(),
    dateOfExpiry: z.string().nullable(),
    storageCondition: z.string().nullable(),
    manufacturer: z.string().nullable(),
    manufacturingSite: z.string().nullable(),
    testingLaboratory: z.string().nullable(),
    coaNumber: z.string().nullable(),
    referenceStandard: z.string().nullable(),
    referenceStandardLot: z.string().nullable(),
  }).passthrough(),
  identityTests: identityTestsSchema.nullable().default(null),
  purityTests: purityTestsSchema.nullable().default(null),
  potencyTests: potencyTestsSchema.nullable().default(null),
  conjugationTests: conjugationTestsSchema.nullable().default(null),
  safetyTests: z.object({
    endotoxin: z.number().nullable(),
    endotoxinUnit: z.string().nullable(),
    endotoxinSpec: z.string().nullable(),
    endotoxinPass: z.boolean().nullable(),
    endotoxinMethod: z.string().nullable(),
    sterility: z.string().nullable(),
    sterilityMethod: z.string().nullable(),
    sterilityPass: z.boolean().nullable(),
    mycoplasma: z.string().nullable(),
    mycoplasmaPass: z.boolean().nullable(),
    bioburden: z.number().nullable(),
    bioburdenPass: z.boolean().nullable(),
  }).passthrough().nullable().default(null),
  physicalTests: z.object({
    appearance: z.string().nullable(),
    appearanceSpec: z.string().nullable(),
    appearancePass: z.boolean().nullable(),
    ph: z.number().nullable(),
    phSpec: z.string().nullable(),
    phPass: z.boolean().nullable(),
    osmolality: z.number().nullable(),
    osmolalityUnit: z.string().nullable(),
    osmolalityPass: z.boolean().nullable(),
    concentration: z.number().nullable(),
    concentrationUnit: z.string().nullable(),
    concentrationMethod: z.string().nullable(),
    concentrationPass: z.boolean().nullable(),
    particulatesMatter: z.string().nullable(),
    particulatesPass: z.boolean().nullable(),
  }).passthrough().nullable().default(null),
  allTests: z.array(testResultSchema).default([]),
  overallResult: z.object({
    disposition: z.enum(["pass", "fail", "conditional", "pending"]).nullable(),
    approvedBy: z.string().nullable(),
    approvalDate: z.string().nullable(),
    qaReviewedBy: z.string().nullable(),
    comments: z.string().nullable(),
  }).passthrough(),
  extractionNotes: z.array(z.string()).default([]),
}).passthrough();

export type CertificateOfAnalysisData = z.infer<typeof certificateOfAnalysisSchema>;
