import Link from "next/link";
import {
  Landmark,
  Building2,
  Handshake,
  Building,
  ShieldCheck,
} from "lucide-react";

export function MarketingFooter() {
  return (
    <footer className="w-full border-t border-border/50">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-5">
          {/* Brand */}
          <div className="col-span-2 sm:col-span-1">
            <div className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                <Landmark className="h-4 w-4" />
              </div>
              <span className="text-lg font-semibold tracking-tight text-foreground">
                OpenShut
              </span>
            </div>
            <p className="mt-3 text-sm text-muted-foreground leading-relaxed max-w-xs">
              Legal document automation for private equity, lending, and fund administration.
            </p>
          </div>

          {/* Products */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Products</h4>
            <ul className="space-y-2">
              {[
                { label: "Lending", icon: Landmark, href: "/lending" },
                { label: "Capital", icon: Building2, href: "/capital" },
                { label: "Deals / M&A", icon: Handshake, href: "/deals" },
                { label: "Syndication", icon: Building, href: "/syndication" },
                { label: "Compliance", icon: ShieldCheck, href: "/compliance" },
              ].map((mod) => (
                <li key={mod.label}>
                  <Link
                    href={mod.href}
                    className="group flex items-center gap-1.5 text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground"
                  >
                    <mod.icon className="h-3 w-3 transition-transform duration-150 group-hover:scale-110" />
                    {mod.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Platform */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Platform</h4>
            <ul className="space-y-2">
              <li>
                <Link href="/platform" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Security & Compliance
                </Link>
              </li>
              <li>
                <Link href="/pricing" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Pricing
                </Link>
              </li>
            </ul>
          </div>

          {/* Company */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Company</h4>
            <ul className="space-y-2">
              <li>
                <span className="text-sm text-muted-foreground">OpenShut LLC</span>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Legal</h4>
            <ul className="space-y-2">
              <li>
                <Link href="/privacy" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/terms" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Terms of Service
                </Link>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-border/50">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <span className="text-sm text-muted-foreground">
              &copy; {new Date().getFullYear()} OpenShut LLC. All rights reserved.
            </span>
          </div>
          <p className="mt-4 text-xs text-muted-foreground/60 max-w-3xl">
            All documents generated by this platform are for informational purposes and should be
            reviewed before execution. This platform does not provide legal advice. Regulatory
            compliance checks are based on publicly available federal and state statutes and are
            not a substitute for independent professional review.
          </p>
        </div>
      </div>
    </footer>
  );
}
