import Link from "next/link";
import { Landmark, TestTubes } from "lucide-react";

export function MarketingFooter() {
  return (
    <footer className="w-full border-t border-border/50">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-5">
          {/* Brand */}
          <div className="col-span-2 sm:col-span-1">
            <div className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                <Landmark className="h-4 w-4" />
              </div>
              <span className="text-lg font-semibold tracking-tight text-foreground">
                OpenShut
              </span>
            </div>
            <p className="mt-3 text-sm text-muted-foreground leading-relaxed max-w-xs">
              AI-powered platforms for lending and biopharma regulatory submissions.
            </p>
          </div>

          {/* Products */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Products</h4>
            <ul className="space-y-2">
              <li>
                <Link href="/" className="group flex items-center gap-1.5 text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  <Landmark className="h-3 w-3 transition-transform duration-150 group-hover:scale-110" />
                  OpenShut Lending
                </Link>
              </li>
              <li>
                <Link href="/bio" className="group flex items-center gap-1.5 text-sm text-muted-foreground transition-colors duration-150 hover:text-emerald-500">
                  <TestTubes className="h-3 w-3 transition-transform duration-150 group-hover:scale-110" />
                  OpenShut Bio
                </Link>
              </li>
            </ul>
          </div>

          {/* Lending */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Lending</h4>
            <ul className="space-y-2">
              <li>
                <Link href="/#features" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Features
                </Link>
              </li>
              <li>
                <Link href="/#programs" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Loan Programs
                </Link>
              </li>
              <li>
                <Link href="/#pricing" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-foreground">
                  Pricing
                </Link>
              </li>
            </ul>
          </div>

          {/* Bio */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Bio</h4>
            <ul className="space-y-2">
              <li>
                <Link href="/bio" className="text-sm text-muted-foreground transition-colors duration-150 hover:text-emerald-500">
                  OpenShut Bio
                </Link>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Legal</h4>
            <ul className="space-y-2">
              <li>
                <span className="text-sm text-muted-foreground">Privacy Policy</span>
              </li>
              <li>
                <span className="text-sm text-muted-foreground">Terms of Service</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-border/50">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <span className="text-sm text-muted-foreground">
              &copy; {new Date().getFullYear()} OpenShut. All rights reserved.
            </span>
          </div>
          <p className="mt-4 text-xs text-muted-foreground/60 max-w-3xl">
            All documents generated by this platform are for informational purposes and should be
            reviewed by qualified legal counsel prior to execution. This platform does not provide
            legal advice. Regulatory compliance checks are based on publicly available federal and
            state statutes and are not a substitute for independent legal review.
          </p>
        </div>
      </div>
    </footer>
  );
}
