import Link from "next/link";
import { Landmark } from "lucide-react";

export function MarketingFooter() {
  return (
    <footer className="w-full border-t border-border/50">
      <div className="mx-auto max-w-6xl px-6 py-12">
        <div className="grid grid-cols-2 gap-8 sm:grid-cols-4">
          {/* Brand */}
          <div className="col-span-2 sm:col-span-1">
            <Link href="/" className="flex items-center gap-2.5">
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground">
                <Landmark className="h-4 w-4" />
              </div>
              <span className="text-lg font-semibold tracking-tight text-foreground">
                OpenShut
              </span>
            </Link>
            <p className="mt-3 text-sm text-muted-foreground leading-relaxed max-w-xs">
              AI-powered loan origination. From borrower file to ready-to-sign deal terms.
            </p>
          </div>

          {/* Product */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Product</h4>
            <ul className="space-y-2">
              <li>
                <Link href="/features" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  Features
                </Link>
              </li>
              <li>
                <Link href="/how-it-works" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  How It Works
                </Link>
              </li>
              <li>
                <Link href="/programs" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  Loan Programs
                </Link>
              </li>
              <li>
                <Link href="/pricing" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                  Pricing
                </Link>
              </li>
            </ul>
          </div>

          {/* Legal */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Legal</h4>
            <ul className="space-y-2">
              <li>
                <span className="text-sm text-muted-foreground">Privacy Policy</span>
              </li>
              <li>
                <span className="text-sm text-muted-foreground">Terms of Service</span>
              </li>
            </ul>
          </div>

          {/* Resources */}
          <div>
            <h4 className="text-sm font-semibold text-foreground mb-3">Resources</h4>
            <ul className="space-y-2">
              <li>
                <span className="text-sm text-muted-foreground">Documentation</span>
              </li>
              <li>
                <span className="text-sm text-muted-foreground">Support</span>
              </li>
            </ul>
          </div>
        </div>

        <div className="mt-10 pt-6 border-t border-border/50">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
            <span className="text-sm text-muted-foreground">
              &copy; {new Date().getFullYear()} OpenShut. All rights reserved.
            </span>
          </div>
          <p className="mt-4 text-xs text-muted-foreground/60 max-w-3xl">
            All documents generated by this platform are for informational purposes and should be
            reviewed by qualified legal counsel prior to execution. This platform does not provide
            legal advice. Regulatory compliance checks are based on publicly available federal and
            state statutes and are not a substitute for independent legal review.
          </p>
        </div>
      </div>
    </footer>
  );
}
