import type { Metadata } from "next";
import Link from "next/link";
import { MarketingNav } from "@/components/marketing-nav";
import { MarketingFooter } from "@/components/marketing-footer";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "OpenShut terms of service. License terms, usage policies, and service agreements.",
  alternates: { canonical: "https://openshut.me/terms" },
};

export default function TermsPage() {
  return (
    <div className="flex min-h-[100dvh] flex-col bg-background">
      <MarketingNav />
      <main className="flex-1 mx-auto max-w-3xl px-6 pt-28 pb-24 sm:pt-36">
        <h1 className="text-3xl font-bold tracking-tight text-foreground mb-8">Terms of Service</h1>
        <div className="prose prose-sm prose-invert max-w-none space-y-6 text-muted-foreground leading-relaxed">
          <p className="text-sm text-muted-foreground/70">Last updated: February 14, 2026</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">1. Acceptance of Terms</h2>
          <p>By accessing or using the OpenShut platform, you agree to be bound by these Terms of Service. If you are using the platform on behalf of an organization, you represent that you have the authority to bind that organization to these terms.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">2. Service Description</h2>
          <p>OpenShut provides legal document automation software for private equity firms, family offices, and institutional lenders. The platform generates documents based on data you provide. OpenShut does not provide legal advice. All generated documents should be reviewed by qualified legal counsel before execution.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">3. License</h2>
          <p>Subject to payment of applicable license fees, we grant you a non-exclusive, non-transferable license to access and use the platform for your internal business purposes. The license is limited to the modules and seat count specified in your agreement.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">4. Your Data</h2>
          <p>You retain all rights to the data you upload and the documents generated from your data. We do not claim ownership of your content. We process your data solely to provide the services you request.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">5. Sample Deals</h2>
          <p>The platform offers sample deals using pre-loaded data. Sample deals are provided for evaluation purposes. You may not upload your own documents until you have an active license.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">6. Acceptable Use</h2>
          <p>You agree not to reverse engineer, decompile, or disassemble any part of the platform. You agree not to use the platform to generate documents for unlawful purposes. You are responsible for the accuracy of the data you provide.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">7. Payment</h2>
          <p>License fees are due upon execution of your agreement. Monthly subscription fees are billed in advance. All fees are non-refundable except as required by law. Additional seats are billed at the rate specified in your agreement.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">8. Limitation of Liability</h2>
          <p>OpenShut is not liable for any decisions made based on documents generated by the platform. The platform is a tool for document preparation, not a substitute for legal counsel. Our total liability is limited to the fees paid in the 12 months preceding the claim.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">9. Termination</h2>
          <p>Either party may terminate the subscription with 30 days written notice. Upon termination, your access to the platform will end at the conclusion of the current billing period. You may export your data before termination.</p>

          <h2 className="text-lg font-semibold text-foreground mt-8">10. Contact</h2>
          <p>For questions about these terms, contact us at <Link href="mailto:legal@openshut.me" className="text-foreground underline">legal@openshut.me</Link>.</p>
        </div>
      </main>
      <MarketingFooter />
    </div>
  );
}
