// =============================================================================
// types.ts
// Shared types for Phase 12: Loan Document Generation
// =============================================================================

// ---------------------------------------------------------------------------
// Input types — data needed to generate any loan document
// ---------------------------------------------------------------------------

export interface DocumentInput {
  // Deal basics
  dealId: string;
  borrowerName: string;
  lenderName: string; // From org config
  guarantorName: string | null; // Separate from borrower (typically the individual principal)
  loanAmount: number;
  loanPurpose: string | null;
  propertyAddress: string | null;
  stateAbbr: string | null;

  // From DealTerms (rules engine output — source of truth for all numbers)
  terms: {
    approvedAmount: number;
    interestRate: number; // decimal, e.g. 0.085
    termMonths: number;
    amortizationMonths: number;
    ltv: number | null;
    monthlyPayment: number;
    baseRateType: string;
    baseRateValue: number;
    spread: number;
    interestOnly: boolean;
    prepaymentPenalty: boolean;
    personalGuaranty: boolean;
    requiresAppraisal: boolean;
    covenants: Covenant[];
    conditions: ConditionItem[];
    specialTerms: Array<SpecialTerm | string> | null;
    fees: Fee[];
    // Late fee terms (rules engine owns these numbers)
    lateFeePercent: number; // e.g. 0.05 for 5%
    lateFeeGraceDays: number; // e.g. 15
  };

  // Loan program context
  programName: string;
  programId: string;
  programCategory: "commercial" | "residential" | "specialty";
  collateralTypes: string[];

  // Optional party/entity fields for multi-party documents
  subordinateCreditorName?: string | null;
  secondLienLenderName?: string | null;
  entityType?: "llc" | "corporation" | "partnership" | "sole_proprietor" | null;

  // UCC debtor fields
  debtorAddress?: string | null;
  debtorStateOfOrganization?: string | null;
  debtorOrganizationId?: string | null;

  // Dates
  generatedAt: Date;
  maturityDate: Date; // computed from generatedAt + termMonths
  firstPaymentDate: Date;
}

export interface Covenant {
  name: string;
  description: string;
  threshold?: number;
  frequency: "annual" | "quarterly" | "monthly";
  source?: string;
}

export interface ConditionItem {
  category: "prior_to_closing" | "prior_to_funding" | "post_closing";
  description: string;
  source: string;
  priority: "required" | "recommended" | "optional";
}

export interface SpecialTerm {
  title: string;
  description: string;
  rationale: string;
}

export interface Fee {
  name: string;
  amount: number;
  description: string;
}

// ---------------------------------------------------------------------------
// AI prose sections — generated by Claude, injected into templates
// ---------------------------------------------------------------------------

/** Keyed by section name. Values are prose strings or string arrays. */
export interface AiDocProse {
  [sectionKey: string]: string | string[];
}

/** Promissory note AI sections */
export interface PromissoryNoteProse {
  defaultProvisions: string;
  accelerationClause: string;
  lateFeeProvision: string;
  waiverProvisions: string;
  governingLawClause: string;
  miscellaneousProvisions: string;
}

/** Loan agreement AI sections */
export interface LoanAgreementProse {
  recitals: string;
  representations: string[];
  eventsOfDefault: string[];
  remediesOnDefault: string;
  waiverAndAmendment: string;
  noticeProvisions: string;
  miscellaneous: string;
  governingLaw: string;
}

/** Security agreement AI sections */
export interface SecurityAgreementProse {
  collateralDescription: string;
  perfectionLanguage: string;
  representationsAndWarranties: string[];
  remediesOnDefault: string;
  dispositionOfCollateral: string;
  governingLaw: string;
}

/** Guaranty agreement AI sections */
export interface GuarantyProse {
  guarantyScope: string;
  waiverOfDefenses: string[];
  subrogationWaiver: string;
  subordination: string;
  miscellaneous: string;
  governingLaw: string;
}

/** Commitment letter AI sections */
export interface CommitmentLetterProse {
  openingParagraph: string;
  conditionsPrecedent: string[];
  representationsRequired: string;
  expirationClause: string;
  governingLaw: string;
}

/** Subordination agreement AI sections */
export interface SubordinationProse {
  subordinationTerms: string;
  seniorDebtDescription: string;
  subordinateDebtDescription: string;
  paymentRestrictions: string;
  standstillProvisions: string;
  turnoverProvisions: string;
  governingLaw: string;
}

/** Intercreditor agreement AI sections */
export interface IntercreditorProse {
  definitionsAndInterpretation: string;
  lienPriority: string;
  paymentWaterfall: string;
  standstillAndCure: string;
  enforcementRights: string;
  purchaseOption: string;
  releaseAndAmendment: string;
  bankruptcyProvisions: string;
  governingLaw: string;
}

/** Environmental indemnity AI sections */
export interface EnvironmentalIndemnityProse {
  indemnificationScope: string;
  representationsAndWarranties: string[];
  covenants: string[];
  remediationObligations: string;
  survivalClause: string;
  governingLaw: string;
}

/** Assignment of leases and rents AI sections */
export interface AssignmentOfLeasesProse {
  assignmentGrant: string;
  representationsAndWarranties: string[];
  covenants: string[];
  lenderRights: string;
  tenantNotification: string;
  governingLaw: string;
}

/** Corporate borrowing resolution AI sections */
export interface CorporateResolutionProse {
  resolutionRecitals: string;        // WHEREAS clauses establishing authority
  authorizationClause: string;       // RESOLVED clause authorizing the loan
  authorizedSigners: string;         // Who is authorized to sign on behalf of entity
  ratificationClause: string;        // Ratification of all prior actions
  certificateOfSecretary: string;    // Secretary/manager certifies the resolution
  governingLaw: string;
}

/** UCC financing statement AI sections */
export interface UccFinancingProse {
  collateralDescription: string;     // Comprehensive UCC Article 9 collateral description
  proceedsClause: string;            // All proceeds and products
  filingInstructions: string;        // Where to file (Secretary of State)
  additionalProvisions: string;      // Any additional provisions
}

/** SNDA AI sections */
export interface SndaProse {
  subordinationTerms: string;
  nonDisturbanceTerms: string;
  attornmentTerms: string;
  lenderProtections: string;
  governingLaw: string;
}

/** Estoppel certificate AI sections */
export interface EstoppelProse {
  additionalCertifications: string;
}

/** Borrower's certificate AI sections */
export interface BorrowersCertificateProse {
  additionalCertifications: string;  // Deal-specific additional certifications
  governingLaw: string;              // Governing law clause
}

/** Legal opinion letter AI sections */
export interface OpinionLetterProse {
  additionalOpinions: string;        // Deal-specific additional legal opinions
  governingLaw: string;              // Governing law clause
}

/** Deed of trust AI sections */
export interface DeedOfTrustProse {
  grantClause: string;
  borrowerCovenants: string[];
  defaultProvisions: string;
  powerOfSale: string;
  environmentalCovenants: string;
  governingLaw: string;
}

/** SBA authorization AI sections */
export interface SbaAuthorizationProse {
  specialConditions: string[];
  useOfProceeds: string;
  governingLaw: string;
}

/** CDC debenture AI sections */
export interface CdcDebentureProse {
  projectDescription: string;
  cdcTermsAndConditions: string;
  governingLaw: string;
}

/** Borrowing base agreement AI sections */
export interface BorrowingBaseProse {
  eligibilityCriteria: string;       // What receivables/inventory qualify as eligible
  advanceRates: string;              // Advance rate percentages and calculation
  reportingRequirements: string;     // Monthly/weekly reporting obligations
  reserveProvisions: string;         // Dilution reserves, concentration limits
  governingLaw: string;
}

/** Digital asset pledge agreement AI sections */
export interface DigitalAssetPledgeProse {
  pledgeGrant: string;               // Grant of security interest in digital assets
  valuationMethodology: string;      // How collateral is valued (exchange, frequency, averaging)
  marginCallProvisions: string;      // LTV triggers, cure periods, top-up requirements
  liquidationProvisions: string;     // Auto-liquidation triggers, process, distribution
  custodyRequirements: string;       // Wallet requirements, key management, approved custodians
  governingLaw: string;
}

/** Digital asset custody agreement AI sections */
export interface CustodyAgreementProse {
  custodyTerms: string;              // Custodian's obligations and standard of care
  accessControl: string;             // Who can access, multi-sig requirements, withdrawal process
  insuranceRequirements: string;     // Insurance on digital assets
  transferProvisions: string;        // How assets are transferred in/out of custody
  terminationProvisions: string;     // How to terminate custody arrangement
  governingLaw: string;
}

// ---------------------------------------------------------------------------
// Output types — results of document generation pipeline
// ---------------------------------------------------------------------------

/** Individual compliance check result — shown to users in the UI */
export interface ComplianceCheck {
  name: string;           // Human-readable name, e.g. "UCC §9-108 Collateral Description"
  regulation: string;     // Regulatory framework, e.g. "Uniform Commercial Code"
  category: "required" | "standard" | "regulatory" | "cross_document";
  passed: boolean;
  note?: string;          // Optional AI explanation if failed
}

export interface LegalIssue {
  severity: "critical" | "warning" | "info";
  section: string;
  description: string;
  recommendation: string;
}

export interface LegalReviewResult {
  passed: boolean;
  issues: LegalIssue[];
  reviewedAt: string;
}

export interface VerificationIssue {
  field: string;
  expected: string;
  found: string;
  severity: "critical" | "warning";
}

export interface VerificationResult {
  passed: boolean;
  issues: VerificationIssue[];
  checksRun: number;
  checksPassed: number;
}

export interface DocumentGenerationResult {
  docType: string;
  docTypeLabel: string;
  buffer: Buffer;
  legalReview: LegalReviewResult;
  verification: VerificationResult;
  complianceChecks: ComplianceCheck[];
  status: "DRAFT" | "REVIEWED" | "FLAGGED";
}

// ---------------------------------------------------------------------------
// Document type registry — maps docType strings to human labels
// ---------------------------------------------------------------------------

export const DOC_TYPE_LABELS: Record<string, string> = {
  promissory_note: "Promissory Note",
  loan_agreement: "Loan Agreement",
  security_agreement: "Security Agreement",
  guaranty: "Guaranty Agreement",
  commitment_letter: "Commitment Letter",
  deed_of_trust: "Deed of Trust",
  closing_disclosure: "Closing Disclosure",
  loan_estimate: "Loan Estimate",
  sba_authorization: "SBA Authorization",
  cdc_debenture: "CDC Debenture",
  assignment_of_leases: "Assignment of Leases & Rents",
  borrowing_base_agreement: "Borrowing Base Agreement",
  ucc_financing_statement: "UCC Financing Statement",
  digital_asset_pledge: "Digital Asset Pledge Agreement",
  custody_agreement: "Custody Agreement",
  subordination_agreement: "Subordination Agreement",
  intercreditor_agreement: "Intercreditor Agreement",
  environmental_indemnity: "Environmental Indemnity Agreement",
  corporate_resolution: "Corporate Borrowing Resolution",
  snda: "Subordination, Non-Disturbance and Attornment Agreement",
  estoppel_certificate: "Tenant Estoppel Certificate",
  settlement_statement: "Settlement Statement",
  borrowers_certificate: "Borrower's Certificate",
  compliance_certificate: "Compliance Certificate",
  amortization_schedule: "Amortization Schedule",
  opinion_letter: "Legal Opinion Letter",
  sba_form_1919: "SBA Form 1919 — Borrower Information Form",
  sba_form_1920: "SBA Form 1920 — Lender's Application for Guaranty",
  sba_form_159: "SBA Form 159 — Fee Disclosure and Compensation Agreement",
  sba_form_148: "SBA Form 148 — Unconditional Guarantee",
  sba_form_1050: "SBA Form 1050 — Settlement Sheet",
  irs_4506c: "IRS Form 4506-C (Tax Transcript Request)",
  irs_w9: "IRS Form W-9 (Taxpayer ID)",
  flood_determination: "Standard Flood Hazard Determination",
  privacy_notice: "Privacy Notice (GLBA)",
  patriot_act_notice: "USA PATRIOT Act Notice",
  disbursement_authorization: "Disbursement Authorization",
};
